service:
  name: yyt-chat

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'

functions:
  seeTopicMembers:
    handler: src/admin/topic.seeTopicMembers
    events:
      - http:
          method: get
          path: redis/{topic}
    environment:
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PASSWORD: ${env:REDIS_PASSWORD}
  deleteTopic:
    handler: src/admin/topic.deleteTopic
    events:
      - http:
          method: delete
          path: redis/{topic}
    environment:
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PASSWORD: ${env:REDIS_PASSWORD}
  connect:
    handler: src/ws/connection.connect
    events:
      - websocket:
          route: $connect
    environment:
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PASSWORD: ${env:REDIS_PASSWORD}
  disconnect:
    handler: src/ws/connection.disconnect
    events:
      - websocket:
          route: $disconnect
    environment:
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PASSWORD: ${env:REDIS_PASSWORD}
  defaultMessages:
    handler: src/ws/connection.defaultMessages
    events:
      - websocket:
          route: $default
    environment:
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PASSWORD: ${env:REDIS_PASSWORD}
  subscribeTopic:
    handler: src/ws/topic.subscribeTopic
    events:
      - websocket:
          route: subscribe
    environment:
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PASSWORD: ${env:REDIS_PASSWORD}
  unsubscribeTopic:
    handler: src/ws/topic.unsubscribeTopic
    events:
      - websocket:
          route: unsubscribe
    environment:
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PASSWORD: ${env:REDIS_PASSWORD}
  broadcastMessage:
    handler: src/ws/broadcast.broadcastMessage
    events:
      - websocket:
          route: broadcast
    environment:
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PASSWORD: ${env:REDIS_PASSWORD}
