service:
  name: yyt-message-topic

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: production
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'
  environment:
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    AUTH_URL: ${env:AUTH_URL}
    API_PATH: ${env:API_PATH}

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: # enable auto-packing of external modules
      forceExclude:
        - aws-sdk

functions:
  seeTopicMembers:
    handler: src/admin/topic.seeTopicMembers
    events:
      - http:
          method: get
          path: redis/{topic}
    environment:
      ADMIN_SECRET: ${env:ADMIN_SECRET}
  deleteTopic:
    handler: src/admin/topic.deleteTopic
    events:
      - http:
          method: delete
          path: redis/{topic}
    environment:
      ADMIN_SECRET: ${env:ADMIN_SECRET}

  connect:
    handler: src/ws/connection.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: src/ws/connection.disconnect
    events:
      - websocket:
          route: $disconnect
  defaultMessages:
    handler: src/ws/connection.defaultMessages
    events:
      - websocket:
          route: $default
  subscribeTopic:
    handler: src/ws/topic.subscribeTopic
    events:
      - websocket:
          route: subscribe
  unsubscribeTopic:
    handler: src/ws/topic.unsubscribeTopic
    events:
      - websocket:
          route: unsubscribe
  broadcastMessage:
    handler: src/ws/broadcast.broadcastMessage
    events:
      - websocket:
          route: broadcast
